from __future__ import annotations

import argparse
import itertools
import json
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Subset
from tqdm import trange

from .losses import multilabel_focal_loss, temporal_consistency
from .metrics import multilabel_metrics
from .model import IBPK360Model
from .predicted_relation_data import PredictedTemporalRelationDataset
from .predicted_tracklets import sha256_file
from .protocol import (
    ModelConfig,
    OBJECT_CLASSES,
    SPATIAL_PREDICATES,
    TEMPORAL_PREDICATES,
    validate_protocol,
)
from .relation_data import SpatialRelationDataset
from .train_stage1 import object_class_statistics
from .train_stage2_warmup import (
    encode_tracklets,
    join_objects,
    move_object,
    next_or_none,
    predicate_pos_weight,
    save_checkpoint,
    seed_everything,
    split_encoded,
)


def predicted_temporal_pos_weight(
    dataset: PredictedTemporalRelationDataset, maximum: float
) -> tuple[torch.Tensor, list[int], int]:
    positives = np.zeros(len(TEMPORAL_PREDICATES), dtype=np.int64)
    total = 0
    for shard, local_rows in zip(dataset.shards, dataset.eligible_by_shard):
        if not local_rows:
            continue
        _, relations, _ = shard.open()
        targets = np.asarray(relations["temporal"]["targets"][local_rows], dtype=np.uint8)
        positives += targets.sum(axis=0, dtype=np.int64)
        total += len(targets)
    weights = np.ones(len(TEMPORAL_PREDICATES), dtype=np.float32)
    supported = positives > 0
    weights[supported] = (total - positives[supported]) / positives[supported]
    return torch.from_numpy(np.clip(weights, 1.0, maximum)), positives.tolist(), total


def association_summary(report_paths: list[Path]) -> dict[str, float | int]:
    correct = decisions = predicted_links = true_links = correct_links = 0
    for path in report_paths:
        report = json.loads(path.read_text(encoding="utf-8"))
        correct += int(report["association_correct"])
        decisions += int(report["association_decisions"])
        predicted_links += int(report["predicted_mutual_links"])
        true_links += int(report["true_forward_links"])
        correct_links += int(report["correct_mutual_links"])
    return {
        "association_accuracy": correct / max(decisions, 1),
        "association_correct": correct,
        "association_decisions": decisions,
        "mutual_link_precision": correct_links / max(predicted_links, 1),
        "mutual_link_recall": correct_links / max(true_links, 1),
    }


def validate_track_sources(track_paths: list[Path], expected_sha256: str) -> None:
    for path in track_paths:
        with h5py.File(path.resolve(), "r", swmr=True) as tracks:
            actual = str(tracks.attrs.get("source_checkpoint_sha256", ""))
            if actual != expected_sha256:
                raise ValueError(
                    f"Predicted tracks were not generated by the selected Stage-2 "
                    f"checkpoint: {path}"
                )


def spatial_step(
    model: IBPK360Model,
    batch: dict[str, Any],
    device: torch.device,
    pos_weight: torch.Tensor | None,
    object_weight: torch.Tensor | None,
) -> tuple[dict[str, torch.Tensor], torch.Tensor, torch.Tensor]:
    source = move_object(batch["source"], device)
    target = move_object(batch["target"], device)
    joined = join_objects(source, target)
    outputs = model.encode_objects(**joined)
    count = source["rgb_tokens"].size(0)
    first, second = split_encoded(outputs, count)
    logits = model.predict_spatial(
        first["fused_object"],
        second["fused_object"],
        first["fused_parts"],
        second["fused_parts"],
        batch["geometry"].to(device),
    )
    labels = batch["labels"].to(device)
    node_logits = model.predict_nodes(
        torch.cat([first["fused_object"], second["fused_object"]])
    )
    node_labels = torch.cat(
        [batch["source"]["category_id"], batch["target"]["category_id"]]
    ).to(device)
    return {
        "edge": multilabel_focal_loss(logits, labels, pos_weight=pos_weight),
        "node": F.cross_entropy(node_logits, node_labels, weight=object_weight),
    }, logits.detach(), labels.detach()


def temporal_step(
    model: IBPK360Model,
    batch: dict[str, Any],
    device: torch.device,
    pos_weight: torch.Tensor | None,
) -> tuple[dict[str, torch.Tensor], torch.Tensor, torch.Tensor]:
    source, target, source_mask, target_mask = encode_tracklets(
        model, batch["source"], batch["target"], device
    )
    middle = source["fused_object"].size(1) // 2
    logits = model.predict_temporal(
        source["fused_object"],
        target["fused_object"],
        source_mask,
        target_mask,
        source["fused_parts"][:, middle],
        target["fused_parts"][:, middle],
        batch["geometry"].to(device),
    )
    labels = batch["labels"].to(device)
    source_context = model.temporal(source["fused_object"], source_mask)
    target_context = model.temporal(target["fused_object"], target_mask)
    consistency = 0.5 * (
        temporal_consistency(source_context, source_mask)
        + temporal_consistency(target_context, target_mask)
    )
    return {
        "edge": multilabel_focal_loss(logits, labels, pos_weight=pos_weight),
        "consistency": consistency,
    }, logits.detach(), labels.detach()


def make_loaders(
    features: list[Path],
    relations: list[Path],
    tracks: list[Path],
    batch_size: int,
    shuffle: bool,
) -> tuple[DataLoader | None, DataLoader | None, list[Any]]:
    spatial = SpatialRelationDataset(features, relations)
    temporal = PredictedTemporalRelationDataset(features, relations, tracks)
    spatial_loader = (
        DataLoader(spatial, batch_size=batch_size, shuffle=shuffle) if len(spatial) else None
    )
    temporal_rows = temporal.eligible_indices if shuffle else list(range(len(temporal)))
    temporal_loader = (
        DataLoader(Subset(temporal, temporal_rows), batch_size=batch_size, shuffle=shuffle)
        if temporal_rows
        else None
    )
    return spatial_loader, temporal_loader, [spatial, temporal]


@torch.inference_mode()
def evaluate(
    model: IBPK360Model,
    spatial_loader: DataLoader | None,
    temporal_loader: DataLoader | None,
    device: torch.device,
    spatial_pos_weight: torch.Tensor,
    temporal_pos_weight: torch.Tensor,
    object_weight: torch.Tensor,
    association: dict[str, float | int],
    max_batches: int | None = None,
) -> dict[str, Any]:
    model.eval()
    spatial_logits: list[torch.Tensor] = []
    spatial_labels: list[torch.Tensor] = []
    temporal_logits: list[torch.Tensor] = []
    temporal_labels: list[torch.Tensor] = []
    temporal_available: list[torch.Tensor] = []
    if spatial_loader is not None:
        for index, batch in enumerate(spatial_loader):
            if max_batches is not None and index >= max_batches:
                break
            _, logits, labels = spatial_step(
                model, batch, device, spatial_pos_weight, object_weight
            )
            spatial_logits.append(logits.cpu())
            spatial_labels.append(labels.cpu())
    if temporal_loader is not None:
        for index, batch in enumerate(temporal_loader):
            if max_batches is not None and index >= max_batches:
                break
            _, logits, labels = temporal_step(model, batch, device, temporal_pos_weight)
            available = batch["available"].bool()
            logits = logits.cpu()
            logits[~available] = -20.0
            temporal_logits.append(logits)
            temporal_labels.append(labels.cpu())
            temporal_available.append(available)
    spatial_metrics = (
        multilabel_metrics(
            torch.cat(spatial_logits), torch.cat(spatial_labels), SPATIAL_PREDICATES
        )
        if spatial_logits
        else None
    )
    temporal_metrics = (
        multilabel_metrics(
            torch.cat(temporal_logits), torch.cat(temporal_labels), TEMPORAL_PREDICATES
        )
        if temporal_logits
        else None
    )
    available_metrics = None
    if temporal_logits:
        logits = torch.cat(temporal_logits)
        labels = torch.cat(temporal_labels)
        available = torch.cat(temporal_available)
        if available.any():
            available_metrics = multilabel_metrics(
                logits[available], labels[available], TEMPORAL_PREDICATES
            )
    values = [
        float(spatial_metrics["mean_average_precision"] or 0.0),
        float(temporal_metrics["mean_average_precision"] or 0.0),
        float(association["association_accuracy"]),
    ]
    return {
        "spatial": spatial_metrics,
        "temporal_end_to_end": temporal_metrics,
        "temporal_available_tracklets_only_diagnostic": available_metrics,
        "predicted_tracklet_coverage": (
            float(torch.cat(temporal_available).float().mean()) if temporal_available else 0.0
        ),
        **association,
        "selection_score": float(sum(values) / len(values)),
    }


def train(args: argparse.Namespace) -> dict[str, Any]:
    seed_everything(args.seed)
    device = torch.device(args.device)
    if {path.resolve() for path in args.train_features} & {
        path.resolve() for path in args.val_features
    }:
        raise ValueError("Stage-3 training and validation feature shards overlap.")
    train_spatial, train_temporal, train_datasets = make_loaders(
        args.train_features,
        args.train_relations,
        args.train_tracks,
        args.batch_size,
        True,
    )
    val_spatial, val_temporal, val_datasets = make_loaders(
        args.val_features,
        args.val_relations,
        args.val_tracks,
        args.batch_size,
        False,
    )
    if train_spatial is None or train_temporal is None:
        raise RuntimeError("Stage 3 requires spatial and predicted-temporal training examples.")
    train_predicted = train_datasets[1]
    spatial_weight, spatial_counts, spatial_examples = predicate_pos_weight(
        args.train_relations,
        "spatial",
        len(SPATIAL_PREDICATES),
        args.max_predicate_pos_weight,
    )
    temporal_weight, temporal_counts, temporal_examples = predicted_temporal_pos_weight(
        train_predicted, args.max_predicate_pos_weight
    )
    object_weight, object_counts = object_class_statistics(
        args.train_features,
        len(OBJECT_CLASSES),
        args.max_object_class_weight,
        True,
    )
    spatial_weight = spatial_weight.to(device)
    temporal_weight = temporal_weight.to(device)
    object_weight = object_weight.to(device)
    source_checkpoint = torch.load(
        args.stage2_checkpoint, map_location=device, weights_only=False
    )
    stage2_checkpoint_sha256 = sha256_file(args.stage2_checkpoint.resolve())
    validate_track_sources(
        [*args.train_tracks, *args.val_tracks], stage2_checkpoint_sha256
    )
    model_config = ModelConfig(**source_checkpoint["model_config"])
    validate_protocol(model_config)
    model = IBPK360Model(model_config).to(device)
    model.load_state_dict(source_checkpoint["model"])
    for parameter in itertools.chain(
        model.object_encoder.parameters(), model.association.parameters()
    ):
        parameter.requires_grad_(False)
    trainable = [parameter for parameter in model.parameters() if parameter.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable, lr=args.learning_rate, weight_decay=args.weight_decay
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    history: list[dict[str, Any]] = []
    best_score = -1.0
    start_epoch = 1
    if args.resume and args.last_checkpoint.is_file():
        checkpoint = torch.load(args.last_checkpoint, map_location=device, weights_only=False)
        model.load_state_dict(checkpoint["model"])
        optimizer.load_state_dict(checkpoint["optimizer"])
        scheduler.load_state_dict(checkpoint["scheduler"])
        history = list(checkpoint.get("history", []))
        best_score = float(checkpoint.get("best_selection_score", -1.0))
        start_epoch = int(checkpoint["epoch"]) + 1
    train_association = association_summary(
        [path.with_suffix(".report.json") for path in args.train_tracks]
    )
    val_association = association_summary(
        [path.with_suffix(".report.json") for path in args.val_tracks]
    )
    for epoch in range(start_epoch, args.epochs + 1):
        model.train()
        model.object_encoder.eval()
        model.association.eval()
        spatial_iterator = iter(train_spatial)
        temporal_iterator = iter(train_temporal)
        totals = {"total": 0.0, "spatial": 0.0, "temporal": 0.0, "node": 0.0, "consistency": 0.0}
        progress = trange(args.steps_per_epoch, desc=f"Stage 3 predicted tracks {epoch}/{args.epochs}")
        for step_index in progress:
            optimizer.zero_grad(set_to_none=True)
            spatial_batch, spatial_iterator = next_or_none(spatial_iterator, train_spatial)
            temporal_batch, temporal_iterator = next_or_none(temporal_iterator, train_temporal)
            spatial_losses, _, _ = spatial_step(
                model, spatial_batch, device, spatial_weight, object_weight
            )
            temporal_losses, _, _ = temporal_step(
                model, temporal_batch, device, temporal_weight
            )
            total = (
                args.lambda_spatial * spatial_losses["edge"]
                + args.lambda_temporal * temporal_losses["edge"]
                + args.lambda_node * spatial_losses["node"]
                + args.lambda_consistency * temporal_losses["consistency"]
            )
            total.backward()
            torch.nn.utils.clip_grad_norm_(trainable, args.grad_clip)
            optimizer.step()
            totals["total"] += float(total.detach().cpu())
            totals["spatial"] += float(spatial_losses["edge"].detach().cpu())
            totals["temporal"] += float(temporal_losses["edge"].detach().cpu())
            totals["node"] += float(spatial_losses["node"].detach().cpu())
            totals["consistency"] += float(temporal_losses["consistency"].detach().cpu())
            progress.set_postfix(
                {key: round(value / (step_index + 1), 4) for key, value in totals.items()}
            )
        scheduler.step()
        validation = evaluate(
            model,
            val_spatial,
            val_temporal,
            device,
            spatial_weight,
            temporal_weight,
            object_weight,
            val_association,
            args.max_val_batches,
        )
        record = {
            "epoch": epoch,
            "train": {key: value / args.steps_per_epoch for key, value in totals.items()},
            "train_association": train_association,
            "validation": validation,
        }
        history.append(record)
        print(json.dumps(record, indent=2))
        payload = {
            "schema_version": "IBP-K360-stage3-predicted-tracklet-v1.0.0",
            "teacher_forced_tracklets": False,
            "final_predicted_tracklet_checkpoint": True,
            "held_out_test_evaluated": False,
            "association_source_checkpoint_sha256": stage2_checkpoint_sha256,
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_selection_score": max(best_score, validation["selection_score"]),
            "history": history,
            "model_config": model.config.to_dict(),
            "object_classes": list(OBJECT_CLASSES),
            "spatial_predicates": list(SPATIAL_PREDICATES),
            "temporal_predicates": list(TEMPORAL_PREDICATES),
            "training_statistics": {
                "object_class_counts": object_counts,
                "spatial_examples": spatial_examples,
                "spatial_positive_counts": spatial_counts,
                "temporal_predicted_tracklet_examples": temporal_examples,
                "temporal_positive_counts": temporal_counts,
                "train_predicted_tracklet_availability": train_predicted.availability_by_shard,
                "validation_predicted_tracklet_availability": val_datasets[1].availability_by_shard,
            },
        }
        save_checkpoint(args.last_checkpoint, payload)
        if validation["selection_score"] > best_score:
            best_score = validation["selection_score"]
            save_checkpoint(args.best_checkpoint, payload)
    result = {
        "schema_version": "IBP-K360-stage3-predicted-tracklet-result-v1.0.0",
        "teacher_forced_tracklets": False,
        "held_out_test_evaluated": False,
        "enabled_modalities": list(model.config.enabled_modalities),
        "use_parts": model.config.use_parts,
        "association_source_checkpoint_sha256": stage2_checkpoint_sha256,
        "best_validation_selection_score": best_score,
        "best_checkpoint": str(args.best_checkpoint.resolve()),
        "next_required_stage": "one-time held-out test evaluation and ablations",
    }
    args.output_root.mkdir(parents=True, exist_ok=True)
    args.result.write_text(json.dumps(result, indent=2), encoding="utf-8")
    for dataset in itertools.chain(train_datasets, val_datasets):
        dataset.close()
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune KITTI-360 IBP graph heads on predicted tracklets."
    )
    for split in ("train", "val"):
        parser.add_argument(f"--{split}-features", type=Path, nargs="+", required=True)
        parser.add_argument(f"--{split}-relations", type=Path, nargs="+", required=True)
        parser.add_argument(f"--{split}-tracks", type=Path, nargs="+", required=True)
    parser.add_argument("--stage2-checkpoint", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--steps-per-epoch", type=int, default=1000)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--learning-rate", type=float, default=5e-5)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--lambda-node", type=float, default=0.5)
    parser.add_argument("--lambda-spatial", type=float, default=1.0)
    parser.add_argument("--lambda-temporal", type=float, default=1.0)
    parser.add_argument("--lambda-consistency", type=float, default=0.2)
    parser.add_argument("--max-object-class-weight", type=float, default=5.0)
    parser.add_argument("--max-predicate-pos-weight", type=float, default=20.0)
    parser.add_argument("--grad-clip", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--max-val-batches", type=int)
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()
    for split in ("train", "val"):
        sizes = {
            len(getattr(args, f"{split}_features")),
            len(getattr(args, f"{split}_relations")),
            len(getattr(args, f"{split}_tracks")),
        }
        if len(sizes) != 1:
            parser.error(f"{split} feature, relation, and track shard counts must match")
    args.best_checkpoint = args.output_root / "checkpoints/stage3_best.pt"
    args.last_checkpoint = args.output_root / "checkpoints/stage3_last.pt"
    args.result = args.output_root / "stage3_result.json"
    return args


def main() -> None:
    print(json.dumps(train(parse_args()), indent=2))


if __name__ == "__main__":
    main()
